ALTER TABLE company_phones DROP CONSTRAINT FK_company_phone;
ALTER TABLE company_phones DROP INDEX IX_phone;
ALTER TABLE geo DROP CONSTRAINT FK_region;
ALTER TABLE geo DROP CONSTRAINT FK_district;
ALTER TABLE geo DROP CONSTRAINT FK_city;
ALTER TABLE company_geo DROP CONSTRAINT FK_company_geo_company;
ALTER TABLE company_geo DROP CONSTRAINT FK_company_geo_geo;
ALTER TABLE company_geo DROP INDEX UIX_company_geo;

DROP TABLE IF EXISTS company_geo;
DROP TABLE IF EXISTS geo;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS district;
DROP TABLE IF EXISTS region;
DROP TABLE IF EXISTS company_phones;
DROP TABLE IF EXISTS company;
